#!/usr/bin/env python3
"""
UVM环境生成器

生成UVM验证环境模板代码，帮助快速开始验证工作。

使用方法：
    python uvm_env_gen.py --name <module_name> --dut <dut_name> --type [agent|env]

示例：
    python uvm_env_gen.py --name axi_master --dut axi_master_dut --type env
"""

import argparse
from pathlib import Path


def generate_uvm_agent_template(name: str, dut_name: str) -> str:
    """生成UVM Agent模板。"""
    template = """// UVM Agent for {}
// Generated by chip-frontend-verification-engineer skill

`include "uvm_macros.svh"
`include "uvm_pkg.sv"

class {}_agent extends uvm_agent;

  // Virtual Interface
  virtual {}_vif vif;

  // Configuration
  `uvm_object_utils_decl({}_config, "{}_config_t")
  {}_config_t cfg;

  // Sequencer and Driver
  `uvm_decl_sequencer_and_driver({}_seqr, "{}_sequencer", "{}_driver")
  {}_seqr seqr;
  {}_driver driver;

  // Configuration DB
  `uvm_component_utils_decl({}_mon, "{}_monitor", uvm_monitor)
  `uvm_component_utils_decl({}_sbd, "{}_scoreboard", uvm_scoreboard)

  function new(string name = "{}_agent");
    super.new(name);

  // Create virtual interface
  vif = {}_vif::type_id::create("vif");

  // Create configuration object
  cfg = {}_config_t::type_id::create("cfg");

  // Create sequencer
  seqr = {}_seqr::type_id::create("seqr");
  seqr.set_item({}_item::type_id::create("item"));
  `uvm_config_db::set(uvm_config_db::virtual_sequencer, 
                  vif, 
                  "default_seqr", 
                  seqr);

  // Create driver
  driver = {}_driver::type_id::create("driver");
  `uvm_config_db::set(uvm_config_db::virtual_sequencer, 
                  vif, 
                  "default_driver", 
                  driver);

  // Create monitor
  mon = {}_mon::type_id::create("mon");
  `uvm_config_db::set(uvm_config_db::virtual_monitor, 
                  vif, 
                  "default_monitor", 
                  mon);

  // Create scoreboard
  sb = {}_sbd::type_id::create("sb");
  `uvm_config_db::set(uvm_config_db::virtual_scoreboard, 
                  vif, 
                  "default_sb", 
                  sb);

  endfunction
endclass
""".format(name)
    return template


def generate_uvm_env_template(name: str, dut_name: str) -> str:
    """生成UVM环境模板。"""
    template = """// UVM Environment for {}
// Generated by chip-frontend-verification-engineer skill

`include "uvm_macros.svh"
`include "uvm_pkg.sv"
`include "{}_agent.sv"
`include "{}_if.sv"

class {}_env extends uvm_env;

  // Components
  {}_agent              agent;
  {}_scoreboard       sb;
  {}_monitor          mon;
  {}_vif             vif;

  // Virtual sequencer and driver for top level
  `uvm_decl_sequencer_and_driver({}_seqr, "{}_sequencer", "{}_driver")
  {}_seqr seqr;
  {}_driver driver;

  // Configuration DB
  `uvm_object_utils_decl({}_config, "{}_config_t")
  {}_config_t cfg;

  function new(string name = "{}_env");
    super.new(name);

  // Build phase: Create virtual sequencer and driver
  function void build_phase(uvm_phase phase);
      // Create virtual sequencer and driver for top level
      seqr = {}_seqr::type_id::create("seqr");
      driver = {}_driver::type_id::create("driver");
      `uvm_config_db::set(uvm_config_db::virtual_sequencer, 
                        vif, 
                        "default_seqr", 
                        seqr);
      `uvm_config_db::set(uvm_config_db::virtual_sequencer, 
                        vif, 
                        "default_driver", 
                        driver);
    endfunction

  // Connect phase: Connect DUT
  function void connect_phase(uvm_phase phase);
      super.connect_phase(phase);

      if (!`uvm_config_db::get(this, "{}_agent")) begin
        `uvm_report_fatal(get_full_name(), "Agent not set!");
      end

      // Connect agent's virtual interface to real DUT
      agent.vif = vif;
      sb.vif = vif;
      mon.vif = vif;

      // Connect components
      agent.seqr.connect_phase(phase);
      agent.driver.connect_phase(phase);
      mon.connect_phase(phase);

      `uvm_info(get_full_name(), "DUT connected successfully");
    endfunction

  // Run phase: Start test
  task run_phase(uvm_phase phase);
      super.run_phase(phase);

      // Start virtual sequence
      seqr.start(this);

      // Start default sequence (can be overridden)
      seqr.start_default_sequence(this);
    endtask

  // Report phase: Collect and report results
  function void report_phase(uvm_phase phase);
      super.report_phase(phase);

      // Print coverage summary
      sb.report_summary();
    endfunction

endclass
""".format(name)
    return template


def generate_testbench_template(name: str, dut_name: str) -> str:
    """生成Testbench模板。"""
    template = """// UVM Testbench for {}
// Generated by chip-frontend-verification-engineer skill

`include "uvm_macros.svh"
`include "uvm_pkg.sv"
`include "{}_env.sv"

module {}_tb;

  // Clock and Reset
  reg clk;
  reg rst_n;

  // DUT interface
  {}_vif vif;

  // Testbench
  {}_env env;

  initial begin
    // Clock generation
    clk = 0;
    forever #5 clk = ~clk;

    // Reset sequence
    rst_n = 0;
    #100 rst_n = 1;

    // Run UVM test
    `uvm_info("Starting UVM verification");
    run_test();
  end

  task run_test();
    // Set virtual interface
    vif.clk = clk;
    vif.rst_n = rst_n;

    // Run test
    env.run_test();

    // Wait for completion
    #100;
    `uvm_info("Test completed");
    `uvm_info(get_type_name(), "Simulation finished");
  endtask

endmodule
""".format(name)
    return template


def main():
    parser = argparse.ArgumentParser(
        description="UVM环境代码生成器",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--name", required=True, help="模块名称")
    parser.add_argument("--dut", required=True, help="DUT名称")
    parser.add_argument("--type", choices=["agent", "env", "scoreboard", "test"], help="生成类型")
    parser.add_argument("--output", help="输出文件路径")

    args = parser.parse_args()

    if args.type == "agent":
        content = generate_uvm_agent_template(args.name, args.dut)
        filename = "{}_agent.sv".format(args.name)
    elif args.type == "env":
        content = generate_uvm_env_template(args.name, args.dut)
        filename = "{}_env.sv".format(args.name)
    elif args.type == "scoreboard":
        content = generate_uvm_agent_template(args.name, args.dut)
        filename = "{}_sbd.sv".format(args.name)
    elif args.type == "test":
        content = generate_testbench_template(args.name, args.dut)
        filename = "{}_tb.sv".format(args.name)
    else:
        # Generate all
        content = """// UVM Components for {}
// Generated by chip-frontend-verification-engineer skill

{}

{}
{}
{}
{}
""".format(
            args.name,
            generate_uvm_agent_template(args.name, args.dut),
            generate_uvm_env_template(args.name, args.dut),
            generate_testbench_template(args.name, args.dut)
        )
        filename = "{}_uvm_all.sv".format(args.name)

    if args.output:
        output_path = Path(args.output) / filename
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")
        print(f"Generated: {output_path}")
    else:
        print(content)


if __name__ == "__main__":
    main()
